version: '3'

services:

  storybook:
    image: node:8.15.0
    working_dir: /usr/src
    volumes:
      - ./.storybook:/usr/src/.storybook
      - ./components:/usr/src/components
      - ./layouts:/usr/src/layouts
      - ./pages:/usr/src/pages
      - ./index.js:/usr/src/index.js
      - ./package.json:/usr/src/package.json
      - ./package-lock.json:/usr/src/package-lock.json
      - ../assets/scripts:/usr/assets/scripts
      - dist:/usr/src/static
    command: [ 'npm', 'run', 'docker' ]
    ports:
      - 3000:3000

  assets:
    image: node:8.15.0
    working_dir: /usr/src
    volumes:
      - ../assets/scripts:/usr/src/scripts
      - ../assets/styles:/usr/src/styles
      - ../assets/gulpfile.js:/usr/src/gulpfile.js
      - ../assets/package.json:/usr/src/package.json
      - ../assets/package-lock.json:/usr/src/package-lock.json
      - dist:/usr/src/dist
    command: [ 'npm', 'run', 'docker' ]

volumes:
  dist:
  assets:
